# Generated by Django 6.0.1 on 2026-03-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_alter_userprofile_photo_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="input",
            field=models.TextField(max_length=1000),
        ),
    ]
